image: $CI_REGISTRY/elpitech/lpt/containers/arm64-builder:0.0.1

stages:
  - build

variables:
  GIT_DEPTH: 100

.build_kernel_template: &build_kernel_dfn
  stage: build
  tags:
    - kubernetes-xl
  script:
    - rm -f linux-*.deb linux-*.buildinfo linux-*.changes
    - rm -rf ./build
    - make ARCH=arm64 O=./build CROSS_COMPILE=/usr/bin/aarch64-linux-gnu- ${DEFCONFIG}
    - make ARCH=arm64 O=./build CROSS_COMPILE=/usr/bin/aarch64-linux-gnu- bindeb-pkg -j $(nproc)
    - |
      VERSION=$(git describe --tags)
      echo "Uploading version ${VERSION}"
      echo "          branch ${CI_COMMIT_BRANCH}"
      echo "          board ${CPU_TYPE}"
      GIT_TAG=$(git describe --tags --no-abbrev)
      FULL_PATH="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/kernel/${GIT_TAG}/${CPU_TYPE}-${CI_COMMIT_BRANCH}-${VERSION}.tar"
      echo "Full path: ${FULL_PATH}"
      tar cf - --exclude='*-dbg_*' linux-*arm64.deb | curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file - ${FULL_PATH}
    - rm -f linux-*.deb linux-*.buildinfo linux-*.changes

bm1000:
  variables:
    DEFCONFIG: bm1000_defconfig
    CPU_TYPE: "bm1000"
  <<: *build_kernel_dfn

bs1000:
  variables:
    DEFCONFIG: bs1000_defconfig
    CPU_TYPE: "bs1000"
  <<: *build_kernel_dfn
